# the neural network training method to use. Options are 'sgd', 'adagrad', 'windowgrad', 'nesterov'
method = 'adadelta'

# the treshold for buying into a currency. e.g.: The predicted price is 1% above the current candle.close

threshold_buy = 1.00

# the treshold for selling a currency. e.g.: The predicted price is 1% under the current candle.close
threshold_sell = -1.00

# The length of the candle.close price buffer. It's used to train the network on every update cycle.
price_buffer_len = 100

# The learning rate of net - not used for adadelta or adagrad
learning_rate = 0.01


# learning speed - not used for adadelta or adagrad
momentum = 0.9
# l2 decay
decay = 0.1

# minimum number of prictions until the network is considered 'trained'. History size should be equal
min_predictions = 720

# enables stoploss function
stoploss_enabled = false

# trigger stoploss 5% under last buyprice
stoploss_threshold = 0.95